Todo_list/Todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]

Todo_list/base/urls.py
from django.urls import path
from .views import TaskCreate, DeleteView, TaskDetail, TaskList, TaskUpdate, CustomLoginView, RegisterPage
from django.contrib.auth.views import LogoutView

app_name = 'base'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='base:login'),name='logout'),
    path('register/',RegisterPage.as_view(), name='register'),
    path('', TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('task-create/', TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task_update'),
    path('task-delete/<int:pk>/', DeleteView.as_view(), name='task_delete'),

]

Todo_list/base/models.py
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=10000, null=True, blank=True)
    complete_tasks = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

    class Meta:
        ordering = ['complete_tasks']

Todo_list/base/views.py
from django.http import request
from django.shortcuts import redirect, render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import FormView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt


from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from .models import Task

class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('base:tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)


    def get(self, *args, **kwargs): 
        if self.request.user.is_authenticated:
            return redirect('base:tasks')
        return super(RegisterPage, self).get(*args, **kwargs)
# @csrf_exempt
# def register(request):
#     if request.POST == 'POST':
#         form = UserCreationForm()
#         if form.is_valid():
#             form.save()
#         messages.success(request, 'Account created successfully')
    
#     else:
#         form = UserCreationForm()
#         context = { 'form': form}
#     return render(request, 'base/register.html', context)



class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('base:tasks')



class TaskList(LoginRequiredMixin, ListView):
    model =Task
    context_object_name ='tasks'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete_tasks=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(
                 title__startswith=search_input
            )
        context['search_input'] = search_input
        return context
    

class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task.html'

class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description', 'complete_tasks']
    success_url = reverse_lazy('base:tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)

class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'complete_tasks']
    success_url = reverse_lazy('base:tasks')

class DeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task_delete.html'
    success_url = reverse_lazy('base:tasks')

Todo_list/base/templates/base/login.html
{% extends 'base/main.html' %}
{% block content%}

<div class="header-bar">
    <h1>Login</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="login">
    </form>

    <p>Don't you have an account? <a href="{% url 'base:register' %}">Register</a></p>

</div>


{% endblock content %}

Todo_list/base/templates/base/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do Items</title>
    <meta name="description" content="">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300&display=swap" rel="stylesheet">
    <style>
        body {
            background-color: rgb(227, 250, 230);
            font-family: 'Comfortaa', cursive;
            padding-top: 50px ;
        }

        .container{
            max-width: 550px;
            margin: auto;
            border-radius: 15px 15px 5px 5px;
            background-color: white;
            box-shadow: 4px 4px 13px -4px rgba(0,0,0,0.21)

        }

        h1,h2,h3,h4,h5,h6 {
            font-family: 'Comfortaa', cursive ;
        }
        a, p {
            color: #4b5156;
        }
        .button {
            font-family: 'Comfortaa', cursive ;
            border: 1px solid #d53183;
            background-color: #FAFAFA;
            color: #d83b9cd9;
            padding: 10px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;


        }
        input[type=text],
        input[type=password],
        textarea{
            border: 1px solid #d83b9cd9;
            border-radius: 5px;
            padding: 10px;
            width: 90%;
        }

        label {
            padding-top: 10px !important;
            display: block;
        }

        .header-bar {
            display: flex;
            justify-content: space-between;
            color: #fff;
            padding: 10px;
            border-radius: 15px 15px 0 0;
            background: linear-gradient(90deg, #d83b9cd9 0%, #ac307067 50%, #5f053533 100%);

        }
        .header-bar a {
            color: white;
            text-decoration: none;
        }

        .task-wrapper {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 20px;
            background-color: white ;
            border-top: 1px solid rgb(223, 233, 224);
        }
         

        .task-title {
            display: flex;
        }

        .task-title a {

            text-decoration: none;
            color: rosybrown;
            margin-left: 10px;
        }

        .task-complete-icon {
            height: 20px;
            width: 20px;
            background-color: rgb(107, 173, 136);
            border-radius: 50%;
        }

        .task-incomplete-icon{
            height: 20px;
            width: 20px;
            background-color: rgb(211, 197, 211);
            border-radius: 50%;
        }

        .delete-link {
            text-decoration: none;
            font-weight: 900;
            color: red;
            font-size: 22px;
            line-height: 0;
        }

        #add-search-wrapper {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
        }

        #add-link {
            color: rgb(117, 38, 100);
            text-decoration: none;
            font-size: 44px;
            text-shadow: 1px 1px rgb(117, 38, 100);
        }
        .card-body {
            padding: 20px;
        }
    </style>
</head>
<body>
   
    <div class="container">
        {% block content%}

        {% endblock content %}

    </div>


</body>
</html>

Todo_list/base/templates/base/register.html
{% extends 'base/main.html' %}

{% block content %}

<div class="header-bar">
    <h1>Register</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %} 
        <!-- {{form.as_p}} -->
        <p><label>{{form.username.label}}</label></p>
            {{form.username}}
        <p><label>{{form.password1.label}}</label></p>
            {{form.password1}}
        <p><label>{{form.password2.label}}</label></p>
            {{form.password2}}
        <input style="margin-top: 10px;" class="button" type="submit" value="Register">
    </form>
    <p>Already have an account? <a href="{% url 'base:login' %}">Login</a></p>

</div>

{% endblock content %}

Todo_list/base/templates/base/task_delete.html
{% extends 'base/main.html' %}
{% block content%}

<div class="header-bar">
    <a href="{% url 'base:tasks'%}"> &#8592;back</a>

</div>

<div class="card-body">
    <p>Do you want to delete this task? "{{task}}"</p>
    <form method='POST' action="">
        {%csrf_token%}
        {{form.as_p}}
        <input class="button" type="submit" value="Delete">
    </form>

</div>


{% endblock content %}

Todo_list/base/templates/base/task_form.html
{% extends 'base/main.html' %}

{% block content %}

<div class="header-bar">
    <a href="{% url 'base:tasks' %}">&#8592; back</a>
</div>

<div class="card-body">
    <form method='POST' action="">
        {%csrf_token%}
        {{form.as_p}}
        <input class="button" type="submit" value='Submit'>
    </form>
</div>




{%endblock content%}

Todo_list/base/templates/base/task_list.html
{% extends 'base/main.html' %}

{% block content%}

<div class="header-bar">
    <div>
        <h1>Hello, {{request.user|title}}</h1>
        <h3 style="margin: 0%;"> You have <i>{{count}} </i>  incomplete task{{ count|pluralize:"s"}}</h3>
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'base:logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'base:login' %}">Login</a>
    {% endif %}
</div>

<div id="add-search-wrapper">
    <form method="GET" style="margin-top: 20px; display: flex;">
        <input type="text" name='search-area' value="{{search_input}}">
        <input class="button" type="submit" value= "Search">
    </form>

    <a id="add-link" href="{% url 'base:task-create' %}">&#43;</a>
</div>








<div class="task-items-wrapper">
    {% for task in tasks %}
    <div class="task-wrapper">
        {% if task.complete_tasks %}
        <div class="task-title">
            <div class="task-complete-icon"></div>
            <i><s><a href="{% url 'base:task_update' task.id%}">{{task}}</a></s></i>
        </div>
        {% else %}
        <div class="task-title">
            <div class="task-incomplete-icon"></div>
            <a href="{% url 'base:task_update' task.id%}">{{task}}</a>
        </div>
        <a class="delete-link" href="{% url 'base:task_delete' task.id%}">&#215;</a>
        {% endif %}
    </div>

    {% empty %}
    <h3>No items in list</h3> 
    {% endfor %} 
</div>



{% endblock content %}